name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Version
      description: Tell us the environment and tool version under which you came across the bug
      placeholder: |
        Windows version:
        Win32 app isolation release version:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Repro Steps
      description: How did you get this bug?
      placeholder: |
        Please be as specific as possible so we can reproduce the issue
    validations:
      required: true
  - type: textarea
    attributes:
      label: Unexpected Results
      description: Show us how the results were different than what you expected, screenshots or logs might be helpful
    validations:
      required: true
