name: Feature or Enhancement
description: Request a new feature or enhancement for existing features
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    label: Summary
    description: A summary of your request
    validations:
      required: true
  - type: textarea
    label: Pitch
    description: Provide a detailed description for the feature/enhancement
    placeholder: Let us know what you want and why you think this feature/enhancement is helpful
    validations:
      required: true
