name: Inquiry
description: Questions about Win32 app isolation
title: "[Inquiry]: "
labels: ["inquiry"]
body:
  - type: textarea
    label: Description
    description: What's your inquiry?
    validations:
      required: true
